FinalExam/Controllers/AnnouncementController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using FinalExam.DAL.Entities;
using FinalExam.Models;
using FinalExam.Services.Contracts;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace FinalExam.Controllers
{
    public class AnnouncementController : Controller
    {
        private readonly IAnnouncementService _announcementService;
        private readonly UserManager<User> _userManager;

        public AnnouncementController(IAnnouncementService announcementService, UserManager<User> userManager)
        {
            _announcementService = announcementService;
            _userManager = userManager;
        }

        public IActionResult Index(AnnouncementIndexModel model)
        {
            try
            {
                var announceModels = _announcementService.GetAllAnnouncements(model);
                model.Announcements = announceModels;
                return View(model);
            }
            catch(Exception e)
            {
                return StatusCode(500, e.Message);
            }
            
        }

        [Authorize]
        public IActionResult Create()
        {
            var model = _announcementService.GetAllAnnouncementCreateModel();
            return View(model);
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> CreateAnnouncement(AnnouncementCreateModel model)
        {
            try
            {
                User currentUser = await _userManager.GetUserAsync(User);
                _announcementService.CreateAnnouncement(model, currentUser.Id);
                return RedirectToAction("Index");
            }
            catch(Exception e)
            {
                return StatusCode(500, e.Message);
            }
        }

        [Authorize]
        [HttpGet]
        public IActionResult Details(int announcementId)
        {
            var announceModel = _announcementService.GetAnnouncementById(announcementId);

            return View(announceModel);
        }

        [AllowAnonymous]
        [HttpPost]
        public IActionResult Like(int announcementId)
        {
            _announcementService.AddLike(announcementId);

            return RedirectToAction("Index");
        }

        [AllowAnonymous]
        [HttpPost]
        public IActionResult LikeAjax(int announcementId)
        {
            try
            {
                var likes = _announcementService.AddLike(announcementId);

                return Ok(likes);
            }
            catch (Exception e)
            {
                return StatusCode(500, e.Message);
            }
        }

        [Authorize]
        [HttpPost]
        public IActionResult UpAnnouncement(int announcementId)
        {
            try
            {
                var date = _announcementService.UpAnnouncementDate(announcementId);
                return Ok(date);
            }
            catch (Exception e)
            {
                return StatusCode(500, e.Message);
            }
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> AddComment(AddCommentRequestModel model)
        {
            try
            {
                var currentUser = await _userManager.GetUserAsync(User);
                var commentModel = _announcementService.AddComment(model, currentUser);

                return Ok(commentModel);
            }
            catch (Exception e)
            {
                return StatusCode(500, e.Message);
            }
        }

        [Authorize]
        [HttpPost]
        public IActionResult Upload(AddGalleryImageModel model)
        {
            try
            {
                _announcementService.UploadImages(model);
                return RedirectToAction("Details", new { announcementId = model.AnnouncementId });
            }
            catch (Exception e)
            {
                return StatusCode(500, e.Message);
            }
        }

        [Authorize]
        [HttpPost]
        public IActionResult UploadAjax(int announcementId)
        {
            try
            {
                AddGalleryImageModel model = new AddGalleryImageModel()
                {
                    AnnouncementId = announcementId,
                    Images = Request.Form.Files
                };

                var imageModels = _announcementService.UploadImages(model);

                return Ok(imageModels.ToList());
            }
            catch (Exception e)
            {
                return StatusCode(500, e.Message);
            }
        }
    }
}

FinalExam/Views/Announcement/Create.cshtml
@model FinalExam.Models.AnnouncementCreateModel

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create</h1>

<h4>AnnouncementCreateModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="CreateAnnouncement" method="post" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CategoryId" class="control-label"></label>
                <<select asp-for="CategoryId" class="form-control" asp-items="Model.CategoriesSelect"></select>
                
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UserPhone" class="control-label"></label>
                <input asp-for="UserPhone" class="form-control" />
                <span asp-validation-for="UserPhone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Image" class="control-label"></label>
                <input asp-for="Image" type="file" accept="image/*" class="form-control" />
                <span asp-validation-for="Image" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

FinalExam/Views/Announcement/Details.cshtml
@using FinalExam.DAL.Entities
@model FinalExam.Models.AnnouncementModel

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>AnnouncementModel</h4>
    <hr />

    @switch (Model.AnnouncementImageType)
    {
        case AnnouncementImageType.Db:
            if (Model.Image != null && Model.Image.Length > 0)
            {
                <img style="width: 50%; height: 50%" src="data:image/jpeg;base64,@(Convert.ToBase64String(Model.Image))" />
            }
            break;
        case AnnouncementImageType.Disk:
            if (!string.IsNullOrWhiteSpace(Model.ImagePath))
            {
                <img style="width: 50%; height: 50%" src="@Url.Content(Model.ImagePath)" />
            }
            break;
    }
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.DatePublished)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.DatePublished)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.AuthorName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.AuthorName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.UserPhone)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.UserPhone)
        </dd>
        
    </dl>

    <table id="commentsTable" class="table">
        <tbody>
            @foreach (var item in Model.Comments)
            {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.AuthorName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CreatedOn)
                </td>
            </tr>
                <tr>
                    <td colspan="2">
                        @Html.DisplayFor(modelItem => item.Content)
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>
<div id="gallery">
    @foreach (var galleryImage in Model.Images)
    {
        if (galleryImage.Image != null && galleryImage.Image.Length > 0)
        {
            <img style="width: 20%; height: 20%" src="data:image/jpeg;base64,@(Convert.ToBase64String(galleryImage.Image))" />
        }
    }
</div>
<div>
    <div><input type="button" id="addComment" class="btn-primary" value="Comment" /></div>
    <div id="commentForm" style="display: none">
        <div><textarea id="commentText" class="form-control"></textarea></div>
        <div><input type="button" id="sendComment" class="btn-primary" value="Send" /></div>
    </div>
    <br />

    <div><input type="button" onclick="upfunc(@Model.Id)" id="upAnnounce" class="btn-primary" value="Up!" /></div>

    <a asp-action="Index">Back to List</a>
</div>
@{
    var addGalleryImageModel = new AddGalleryImageModel()
    {
        AnnouncementId = Model.Id
    };
}

<partial name="_GalleryImagesPartial" model="@addGalleryImageModel" />

@section Scripts
    {
    <script>

        $('#addComment').click(function () {
            $('#commentForm').val('');
            $('#commentForm').show();
            $('#addComment').hide();
    });

        $('#sendComment').click(function () {

        var comment = $('#commentText').val();
        var announcementId = '@Model.Id';
            $.ajax({
        url: '@Url.Action("AddComment", "Announcement")',
                method: 'POST',
                data: { 'comment': comment, 'announcementId': announcementId },
                dataType: 'JSON',
                error: function (data) {
                console.log(data);
                alert('Error ' + data.status + "\n" + data.responseText);
            },
                success: function (data) {
                    $('#commentForm').hide();
                    $('#addComment').show();
                var authorCell = "<td>" + data.authorName + "</td>";
                var createdOnCell = "<td>" + data.createdOn + "</td>";
                var content = "<td colspan='2'>" + data.content + "</td>";
                var newRow = "<tr>" + authorCell + createdOnCell + "</tr>" + "<tr>" + content + "</tr>";
                    $('#commentsTable tbody').append(newRow);
            }
        });
        });

        const upfunc = (announcementId) => {$.ajax({
                url: '@Url.Action("UpAnnouncement", "Announcement")',
                method: 'POST',
                data: { 'announcementId': announcementId },
                error: function (data) {
                    console.log(data);
                    alert('Error ' + data.status + "\n" + data.responseText);
                },
                success: function (data) {
                    $('#datePublished-' + announcementId).html(data);
                }
            });}

        $('#uploadImages').on('click', function () {
            var files = document.getElementById('uploadFile').files;
            if (files.length > 0) {
                var data = new FormData();
                for (var i = 0; i < files.length; i++) {
                    data.append("file" + i, files[i]);
                }

                $.ajax({
                    type: 'POST',
                    url: '@Url.Action("UploadAjax", "Announcement")' + '/?announcementId=' + $('#announcementId').val(),
                    contentType: false,
                    processData: false,
                    data: data,
                    success: function (data) {
                        for (var i = 0; i < data.length; i++) {
                            var img = '<img style="width: 20%; height: 20%" src="data:image/jpeg;base64,' +
                                data[i].image +
                                '"/>';
                            $('#gallery').append(img);
                        }
                    },
                    error: function(data) {
                        alert(data);
                    }
                });
            }
        })

    </script>
}

FinalExam/Views/Announcement/Index.cshtml
@model AnnouncementIndexModel

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<div class="row">
    <div class="col-md-4">
        <form asp-action="Index" method="get">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Page" value="@Model.Page" />
            <div class="form-group">
                <label asp-for="SearchKey" class="control-label"></label>
                <input asp-for="SearchKey" class="form-control" value="@Model.SearchKey" />
                <span asp-validation-for="SearchKey" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Author" class="control-label"></label>
                <input asp-for="Author" class="form-control" value="@Model.Author" />
                <span asp-validation-for="Author" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateFrom" class="control-label"></label>
                <input asp-for="DateFrom" type="date" class="form-control" value="@Model.DateFrom" />
                <span asp-validation-for="DateFrom" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateTo" class="control-label"></label>
                <input asp-for="DateTo" type="date" class="form-control" value="@Model.DateTo" />
                <span asp-validation-for="DateTo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Search" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>
<partial name="_AnnouncementTablePartial" model="@Model" />
@section Scripts
{
    <partial name="_ScriptsPartial" />
}

FinalExam/Views/Announcement/_AnnouncementTablePartial.cshtml
@model AnnouncementIndexModel

<table class="table">
    <tbody>
        @foreach (var item in Model.Announcements)
        {
            <tr>
                <td id="datePublished-@item.Id">
                    @Html.DisplayFor(modelItem => item.DatePublished)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.AuthorName)
                </td>
               
                <td>
                    @Html.DisplayFor(modelItem => item.Price)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.UserPhone)
                </td>
                <td>
                    <a asp-action="Details" asp-route-announcementId="@item.Id">
                        @Html.DisplayFor(modelItem => item.Title)
                    </a>
                </td>
            </tr>
            <tr>
                <td id="likesCount-@item.Id">
                    @Html.DisplayFor(modelItem => item.Likes)
                </td>
                <td>
                    <input type="button" announcementId="@item.Id" class="btn-primary" value="Like" />
                </td>
            </tr>
        }
    </tbody>
</table>
@if (Model.PagingModel.HasPreviousPage)
{
    @Html.ActionLink("<< Назад", "Index", "Announcement",
        new AnnouncementIndexModel()
        {
            Author = Model.Author,
            SearchKey = Model.SearchKey,
            DateFrom = Model.DateFrom,
            DateTo = Model.DateTo,
            Page = Model.Page - 1
        })
}

<b>@Model.Page</b>

@if (Model.PagingModel.HasNextPage)
{
    @Html.ActionLink("Вперед >>", "Index", "Announcement",
        new AnnouncementIndexModel()
        {
            Author = Model.Author,
            SearchKey = Model.SearchKey,
            DateFrom = Model.DateFrom,
            DateTo = Model.DateTo,
            Page = Model.Page + 1
        })
}

FinalExam/Views/Announcement/_GalleryImagesPartial.cshtml
@model AddGalleryImageModel
<form asp-action="Upload" method="post" enctype="multipart/form-data">
    <input type="hidden" asp-for="AnnouncementId" value="@Model.AnnouncementId" />
    <div class="form-group">
        <label asp-for="Images" class="control-label"></label>
        <input asp-for="Images" type="file" multiple="multiple" accept="image/*" class="form-control" />
        <span asp-validation-for="Images" class="text-danger"></span>
    </div>
    <div class="form-group">
        <input type="submit" value="Upload" class="btn btn-primary" />
    </div>
</form>
<br />
<div>
    <input type="file" multiple="multiple" name="upload" id="uploadFile" />
    <input type="hidden" id="announcementId" value="@Model.AnnouncementId" />
    <input type="button" value="Upload" id="uploadImages" />
</div>